# -*- coding: utf-8 -*-
"""Trabalho

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mzWcmO_wMxrwpaeO1tt8P4z23SAp8im
"""

!pip install -q ucimlrepo

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.dummy import DummyClassifier
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix
)

try:
    concrete = fetch_ucirepo(id=165)
    df = pd.concat([concrete.data.features, concrete.data.targets], axis=1)
except Exception:
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/concrete/compressive/Concrete_Data.xls"
    df = pd.read_excel(url)

df.columns = [
    'cimento', 'escoria', 'cinza_volante', 'agua',
    'superplastificante', 'agregado_graudo', 'agregado_miudo',
    'idade', 'resistencia'
]

df = df.drop_duplicates().reset_index(drop=True)

assert df.isna().sum().sum() == 0
assert (df >= 0).all().all()

df['relacao_ac'] = df['agua'] / df['cimento']

def categorizar_risco(mpa):
    if mpa < 25.0:
        return 'Risco Técnico'
    elif mpa < 35.0:
        return 'Atenção'
    else:
        return 'Baixo Risco'

df['classe_risco'] = df['resistencia'].apply(categorizar_risco)

features = [
    'cimento', 'escoria', 'cinza_volante', 'agua',
    'superplastificante', 'agregado_graudo', 'agregado_miudo',
    'idade', 'relacao_ac'
]

X = df[features]
y_reg = df['resistencia']
y_clf = df['classe_risco']

X_train, X_test, y_reg_train, y_reg_test, y_clf_train, y_clf_test = train_test_split(
    X, y_reg, y_clf, test_size=0.20, random_state=42, stratify=y_clf
)

df_train = X_train.copy()
df_train['resistencia'] = y_reg_train
df_train['classe_risco'] = y_clf_train

regressores = {
    'Linear Simples (Cimento)': Pipeline([
        ('scaler', StandardScaler()),
        ('model', LinearRegression())
    ]),
    'Linear Múltipla': Pipeline([
        ('scaler', StandardScaler()),
        ('model', LinearRegression())
    ]),
    'Polinomial (Grau 2)': Pipeline([
        ('poly', PolynomialFeatures(degree=2, include_bias=False)),
        ('scaler', StandardScaler()),
        ('model', LinearRegression())
    ])
}

resultados_reg = []
preds_reg = {}

y_pred_base_reg = np.full_like(y_reg_test, fill_value=y_reg_train.mean())
resultados_reg.append({
    'Modelo': 'Baseline (Média)',
    'MAE (MPa)': mean_absolute_error(y_reg_test, y_pred_base_reg),
    'RMSE (MPa)': np.sqrt(mean_squared_error(y_reg_test, y_pred_base_reg)),
    'R²': r2_score(y_reg_test, y_pred_base_reg),
    'R² Ajustado': 0.0
})

n_test = len(y_reg_test)

for nome, pipe in regressores.items():
    if nome == 'Linear Simples (Cimento)':
        pipe.fit(X_train[['cimento']], y_reg_train)
        y_pred = pipe.predict(X_test[['cimento']])
        p = 1
    else:
        pipe.fit(X_train, y_reg_train)
        y_pred = pipe.predict(X_test)
        p = pipe.named_steps['poly'].n_output_features_ if 'poly' in pipe.named_steps else X_train.shape[1]

    preds_reg[nome] = y_pred
    mae = mean_absolute_error(y_reg_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_reg_test, y_pred))
    r2 = r2_score(y_reg_test, y_pred)
    r2_adj = 1 - (1 - r2) * (n_test - 1) / (n_test - p - 1)

    resultados_reg.append({
        'Modelo': nome,
        'MAE (MPa)': mae,
        'RMSE (MPa)': rmse,
        'R²': r2,
        'R² Ajustado': r2_adj
    })

df_resultados_reg = pd.DataFrame(resultados_reg)
print("=== TAREFA 1: MODELOS DE REGRESSÃO CONTÍNUA (MPa) ===")
print(df_resultados_reg.to_string(index=False))

classificadores = {
    'Referência (Dummy - Moda)': DummyClassifier(strategy="most_frequent"),
    'Modelo A: Regressão Logística': Pipeline([
        ('scaler', StandardScaler()),
        ('model', LogisticRegression(C=1.0, max_iter=1000, random_state=42))
    ]),
    'Modelo B: KNN (k=5, Manhattan)': Pipeline([
        ('scaler', StandardScaler()),
        ('model', KNeighborsClassifier(n_neighbors=5, metric='manhattan', weights='distance'))
    ])
}

resultados_clf = []
preds_clf = {}
ordem_classes = ['Risco Técnico', 'Atenção', 'Baixo Risco']

for nome, model in classificadores.items():
    model.fit(X_train, y_clf_train)
    y_pred = model.predict(X_test)
    preds_clf[nome] = y_pred

    acc = accuracy_score(y_clf_test, y_pred)
    prec = precision_score(y_clf_test, y_pred, zero_division=0, average='weighted')
    rec = recall_score(y_clf_test, y_pred, average='weighted')
    f1 = f1_score(y_clf_test, y_pred, average='weighted')

    cm_temp = confusion_matrix(y_clf_test, y_pred, labels=ordem_classes)
    rec_risco = cm_temp[0, 0] / cm_temp[0, :].sum() if cm_temp[0, :].sum() > 0 else 0.0

    resultados_clf.append({
        'Modelo': nome,
        'Acurácia': acc,
        'Precisão (Weighted)': prec,
        'Recall (Weighted)': rec,
        'F1-Score (Weighted)': f1,
        'Recall (Risco Técnico)': rec_risco
    })

df_resultados_clf = pd.DataFrame(resultados_clf)
print("\n=== TAREFA 2: MODELOS DE CLASSIFICAÇÃO DE RISCO ===")
print(df_resultados_clf.to_string(index=False))

sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(2, 2, figsize=(15, 11))

sns.heatmap(
    df_train.drop(columns=['classe_risco']).corr(),
    annot=True, cmap='coolwarm', fmt=".2f", ax=axes[0, 0]
)
axes[0, 0].set_title("EDA (Treino): Matriz de Correlação de Pearson")

sns.scatterplot(
    data=df_train, x='idade', y='resistencia',
    hue='classe_risco', palette='viridis', alpha=0.7, ax=axes[0, 1]
)
axes[0, 1].set_title("EDA (Treino): Resistência vs. Idade de Cura")
axes[0, 1].set_xlabel("Idade (dias)")
axes[0, 1].set_ylabel("Resistência (MPa)")

pred_poly = preds_reg['Polinomial (Grau 2)']
residuos_poly = y_reg_test - pred_poly

axes[1, 0].scatter(pred_poly, residuos_poly, alpha=0.6, color='steelblue')
axes[1, 0].axhline(0, color='red', linestyle='--', lw=2)
axes[1, 0].set_title("Diagnóstico de Resíduos: Regressão Polinomial (Grau 2)")
axes[1, 0].set_xlabel("Valores Previstos (MPa)")
axes[1, 0].set_ylabel("Resíduos (e = Real - Previsto)")

cm_knn = confusion_matrix(y_clf_test, preds_clf['Modelo B: KNN (k=5, Manhattan)'], labels=ordem_classes)
sns.heatmap(
    cm_knn, annot=True, fmt='d', cmap='Blues',
    xticklabels=ordem_classes, yticklabels=ordem_classes, ax=axes[1, 1]
)
axes[1, 1].set_title("Matriz de Confusão: Modelo B (KNN)")
axes[1, 1].set_xlabel("Predição do Modelo")
axes[1, 1].set_ylabel("Valor Real")

plt.tight_layout()
plt.show()

modelo_mult = regressores['Linear Múltipla'].named_steps['model']
coefs = pd.Series(modelo_mult.coef_, index=features).sort_values(ascending=False)
print("\n--- COEFICIENTES DA REGRESSÃO LINEAR MÚLTIPLA ---")
print(f"Intercepto (w0): {modelo_mult.intercept_:.4f}")
print(coefs.to_string())